### ISSUE TITLE
TigerPorts suggestions

### ISSUE THREAD

**Issue by rickyzhang82** [ken-cunningham-webuse/TigerPorts#1]
Hi Ken,
As Macport users in Tiger, I really appreciated your initiative. There are a couple of issues we need to discuss to fork it for Tiger. (Please add more if I missed anything)
- As port keeps on upgrading, we need a stable snapshot to the port (must have)
- Build as complete as possible compatible port collections (must have)
- Singed binary port collection (nice to have)

**Comment by ken-cunningham-webuse** [comment]
Hi Ricky; I really appreciate your knowledge and input. 

The great thing about MacPorts is that almost all the ports currently on MacPorts will build on Tiger without any modification -- it's truly fantastic.

What I have here are ports pegged to a 'last compatible' version (where upstream has moved beyond what Tiger is capable of being modified to do), or Portfiles that have been modified to work on Tiger but have not (as yet, at least) been incorporated into the MacPorts port collection for one reason or another. 

If you come across any ports you'd  like to see work on Tiger but currently won't, feel free to point them out, or even better if you like, fix 'em and contribute to the collection!

**Comment by rickyzhang82** [comment]
What's the reason that they don't accept the fix for Tiger? TBH, if fix didn't get push to upstream, many still suffers.

**Comment by ken-cunningham-webuse** [comment]
Sometimes there is an expectation for the fix to be done upstream, which all would agree is always best. Sometimes I think it just doesn't get to the top of the priority list, given the focus on the newer systems, and the fact that a brand new OS just released, with the dozens of tickets that follow that. Only so much time in the day.
